targets:
  ubuntu-14.04:
    dependencies:
      - imagemagick
  ubuntu-12.04:
    dependencies:
      - imagemagick
  debian-7:
    dependencies:
      - imagemagick
services:
  - postgres
  - redis
before_precompile: ./packaging/setup.sh
after:
  - rm lib/tasks/pkgr.rake
