env:
  - DISCOURSE_REDIS_HOST="$REDIS_HOST"
  - DISCOURSE_REDIS_PORT="$REDIS_PORT"
targets:
  ubuntu-16.04:
    dependencies:
      - imagemagick
  ubuntu-14.04:
    dependencies:
      - imagemagick
  debian-8:
    dependencies:
      - imagemagick
services:
  - postgres
  # - redis
before_precompile: ./packaging/setup.sh
after:
  - rm -f lib/tasks/pkgr.rake
